### ISSUE TITLE
Pack definition pack.yml update

### ISSUE THREAD

**Issue by Smeds** [arteria-project/arteria-packs#80]
Would it be possible to update pack.yml file follow the instructions on [stackstorm homepage](https://docs.stackstorm.com/reference/packs.html) for version and naming?

---

A note on metadata: StackStorm enforces certain rules about metadata. The version value in pack.yaml must conform to semver:0.2.5, not 0.2. The name value in pack.yaml must only contain letters, digits, and underscores, unless you set the ref value explicitly in pack.yaml. Finally the email attribute in pack.yaml must contain a properly formatted email address.

---

The new file could look like this:

```
---

name: Arteria Packs
ref: arteria
description: Pack for running sequencing center operations
keywords:
  - sequencing
  - life science
version: 0.1.0
author: Johan Dahlberg
email: johan.dahlberg@medsci.uu.se

```

**Comment by johandahlberg** [comment]
Yes, we need to do a lot of updates for this to be compatible with the latest st2 version. My current plan is that this repo will probably migrated to something like "snpseq.packs". Then we can have a fresh start with a common arteria-packs, that will not be polluted with all of our snp&seq specific stuff. To get started I'd suggest that you start by creating your own repo to try things out, and then we can merge things later. Does that sound alright?

**Comment by Smeds** [comment]
Made a [pull request (Pack.yaml update #81)](https://github.com/arteria-project/arteria-packs/pull/81) of the version we have been running, with stackstorm 2.3.1. Where name and version have been updated to the new requirements.

**Comment by johandahlberg** [comment]
This has been fixed in: https://github.com/arteria-project/arteria-packs/pull/89
